server:
  port: 7010
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/temp?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: non_null # 对象的NULL值属性不转换为JSON


  # 配置Redis
#  redis:
#    host: 192.168.80.9
#    port: 6379


# mybatis-plus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml